# Generated by Django 5.0.2 on 2024-03-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumi_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='ProductInOrder',
        ),
    ]
